In [1]:
import pandas as pd
import numpy as np
import pickle
import os

root = "/home/rodriguez/Documents/UPJV/Sujets_Pathologiques/Luisin_L/"
# Create a list with the names of the csv files in root folder
csv_files = [f for f in os.listdir(root) if f.endswith('.csv')]
print(csv_files)

['M3_1.csv', 'M2_1.csv', 'M4_2.csv', 'M5_3.csv', 'M1_1.csv']

In [2]:
luisin_df = pd.DataFrame(columns=['Name', 'Content'])
for csv in csv_files:
    filepath = root + csv
    print(filepath)
    # Try to read csv file and store its content as a numpy array
    try:
        csv_content = pd.read_csv(filepath, header=None, skiprows=5, usecols=[i+2 for i in range(324)])
        csv_array = csv_content.to_numpy()
        luisin_df = pd.concat([luisin_df, pd.DataFrame({'Name': csv, 'Content': [csv_array]})], ignore_index=True)
    except:
        print("Error while reading csv file. File: " + csv + " ignored.")


luisin_df.head()

/home/rodriguez/Documents/UPJV/Sujets_Pathologiques/Luisin_L/M3_1.csv
/home/rodriguez/Documents/UPJV/Sujets_Pathologiques/Luisin_L/M2_1.csv
/home/rodriguez/Documents/UPJV/Sujets_Pathologiques/Luisin_L/M4_2.csv
/home/rodriguez/Documents/UPJV/Sujets_Pathologiques/Luisin_L/M5_3.csv
/home/rodriguez/Documents/UPJV/Sujets_Pathologiques/Luisin_L/M1_1.csv

       Name                                            Content
0  M3_1.csv  [[155.372742, 147.488144, 1087.77356, 128.5124...
1  M2_1.csv  [[182.946838, 159.988525, 1094.000122, 154.808...
2  M4_2.csv  [[174.043854, 146.83992, 1088.874512, 146.4265...
3  M5_3.csv  [[172.556198, 153.536407, 1086.332031, 144.728...
4  M1_1.csv  [[181.215668, 157.22319, 1092.981812, 153.3298...

In [3]:
luisin_df.rename(columns={"Name": "File name"}, inplace=True)
luisin_df.head()

  File name                                            Content
0  M3_1.csv  [[155.372742, 147.488144, 1087.77356, 128.5124...
1  M2_1.csv  [[182.946838, 159.988525, 1094.000122, 154.808...
2  M4_2.csv  [[174.043854, 146.83992, 1088.874512, 146.4265...
3  M5_3.csv  [[172.556198, 153.536407, 1086.332031, 144.728...
4  M1_1.csv  [[181.215668, 157.22319, 1092.981812, 153.3298...

In [4]:
M_list = [3,2,4,5,1]
luisin_df['Movement'] = M_list

In [7]:
luisin_df.head()

,File name,Content,Movement,Mocap platform,Name,Pathology
0,M3_1.csv,"[[155.372742, 147.488144, 1087.77356, 128.5124...",3,IFF,Luisin L,Facial palsy
1,M2_1.csv,"[[182.946838, 159.988525, 1094.000122, 154.808...",2,IFF,Luisin L,Facial palsy
2,M4_2.csv,"[[174.043854, 146.83992, 1088.874512, 146.4265...",4,IFF,Luisin L,Facial palsy
3,M5_3.csv,"[[172.556198, 153.536407, 1086.332031, 144.728...",5,IFF,Luisin L,Facial palsy
4,M1_1.csv,"[[181.215668, 157.22319, 1092.981812, 153.3298...",1,IFF,Luisin L,Facial palsy

In [6]:
luisin_df["Mocap platform"] = "IFF"
luisin_df["Pathology"] = "Facial palsy"

In [8]:
luisin_df.rename(columns={"Mocap platform": "MoCap platform"}, inplace=True)
luisin_df.head()

,File name,Content,Movement,MoCap platform,Name,Pathology
0,M3_1.csv,"[[155.372742, 147.488144, 1087.77356, 128.5124...",3,IFF,Luisin L,Facial palsy
1,M2_1.csv,"[[182.946838, 159.988525, 1094.000122, 154.808...",2,IFF,Luisin L,Facial palsy
2,M4_2.csv,"[[174.043854, 146.83992, 1088.874512, 146.4265...",4,IFF,Luisin L,Facial palsy
3,M5_3.csv,"[[172.556198, 153.536407, 1086.332031, 144.728...",5,IFF,Luisin L,Facial palsy
4,M1_1.csv,"[[181.215668, 157.22319, 1092.981812, 153.3298...",1,IFF,Luisin L,Facial palsy

In [9]:
luisin_df["Aquisition date"] = "15-09-2022"
luisin_df["Experimentator"] = "Félix"

In [10]:
luisin_df.rename(columns={"Content": "Original SPC"}, inplace=True)
luisin_df.head()

,File name,Original SPC,Movement,MoCap platform,Name,Pathology,Aquisition date,Experimentator
0,M3_1.csv,"[[155.372742, 147.488144, 1087.77356, 128.5124...",3,IFF,Luisin L,Facial palsy,15-09-2022,Félix
1,M2_1.csv,"[[182.946838, 159.988525, 1094.000122, 154.808...",2,IFF,Luisin L,Facial palsy,15-09-2022,Félix
2,M4_2.csv,"[[174.043854, 146.83992, 1088.874512, 146.4265...",4,IFF,Luisin L,Facial palsy,15-09-2022,Félix
3,M5_3.csv,"[[172.556198, 153.536407, 1086.332031, 144.728...",5,IFF,Luisin L,Facial palsy,15-09-2022,Félix
4,M1_1.csv,"[[181.215668, 157.22319, 1092.981812, 153.3298...",1,IFF,Luisin L,Facial palsy,15-09-2022,Félix

In [11]:
luisin_df["Repetitive"] = False
luisin_df.head()

,File name,Original SPC,Movement,MoCap platform,Name,Pathology,Aquisition date,Experimentator,Repetitive
0,M3_1.csv,"[[155.372742, 147.488144, 1087.77356, 128.5124...",3,IFF,Luisin L,Facial palsy,15-09-2022,Félix,False
1,M2_1.csv,"[[182.946838, 159.988525, 1094.000122, 154.808...",2,IFF,Luisin L,Facial palsy,15-09-2022,Félix,False
2,M4_2.csv,"[[174.043854, 146.83992, 1088.874512, 146.4265...",4,IFF,Luisin L,Facial palsy,15-09-2022,Félix,False
3,M5_3.csv,"[[172.556198, 153.536407, 1086.332031, 144.728...",5,IFF,Luisin L,Facial palsy,15-09-2022,Félix,False
4,M1_1.csv,"[[181.215668, 157.22319, 1092.981812, 153.3298...",1,IFF,Luisin L,Facial palsy,15-09-2022,Félix,False

In [14]:
# Save the dataframe as a pickle file
luisin_df.to_pickle("luisin_df.pkl")

In [13]:
luisin_df["Name"] = "LL"